# Generated by Django 6.0.5 on 2026-06-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True, help_text='False = gift card sold out / unavailable.'),
        ),
    ]
