# Generated by Django 6.0.5 on 2026-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersettings_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='title',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='building_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='flat_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
