# Generated by Django 6.0.5 on 2026-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='whatsapp_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
