# Generated by Django 6.0.5 on 2026-06-07 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instamartcategory',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instamartproduct',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instamartstore',
            name='delivery_time',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='instamartstore',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
