# Generated by Django 6.0.5 on 2026-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamart', '0004_instamartcart_instamartcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='instamartorder',
            name='delivery_schedule_type',
            field=models.CharField(default='now', max_length=20),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='gift_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='is_gift',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='recipient_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='instamartorder',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
