# Generated by Django 6.0.5 on 2026-06-22 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamart', '0005_instamartorder_delivery_schedule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instamartstore',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 59), help_text='Daily closing time (HH:MM). Use 23:59 for end-of-day.'),
        ),
        migrations.AddField(
            model_name='instamartstore',
            name='is_24hrs',
            field=models.BooleanField(db_index=True, default=True, help_text='If True, opening/closing times are ignored and the restaurant is always open.'),
        ),
        migrations.AddField(
            model_name='instamartstore',
            name='opening_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Daily opening time (HH:MM). Use 00:00 for midnight-start.'),
        ),
    ]
