# Generated by Django 6.0.5 on 2026-06-02 11:20

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.URLField(blank=True, default='', max_length=500)),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_delivery_time', models.PositiveSmallIntegerField(default=30)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_pure_veg', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_deleted', 'rating'], name='idx_rest_active_rating'), models.Index(fields=['is_active', 'is_pure_veg'], name='idx_rest_veg'), models.Index(fields=['slug'], name='idx_rest_slug')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10, validators=[core.validators.validate_pincode])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[core.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[core.validators.validate_longitude])),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Address',
                'verbose_name_plural': 'Restaurant Addresses',
                'indexes': [models.Index(fields=['city'], name='idx_addr_city'), models.Index(fields=['pincode'], name='idx_addr_pincode')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to='categories.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Category',
                'verbose_name_plural': 'Restaurant Categories',
                'indexes': [models.Index(fields=['restaurant', 'category'], name='idx_restcat_rest_cat')],
                'unique_together': {('restaurant', 'category')},
            },
        ),
    ]
