# Generated by Django 6.0.5 on 2026-06-04 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_phase2_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantBalance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Balance',
                'verbose_name_plural': 'Restaurant Balances',
            },
        ),
    ]
