# Generated by Django 6.0.5 on 2026-06-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantBalance',
        ),
    ]
