# Generated by Django 6.0.5 on 2026-06-16 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_favoriterestaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringMenu',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_plates', models.PositiveIntegerField(default=25)),
                ('cuisine_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_menus', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'catering_menus',
                'ordering': ['price_per_plate'],
            },
        ),
        migrations.CreateModel(
            name='CateringInquiry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField(db_index=True)),
                ('guest_count', models.PositiveIntegerField(default=50)),
                ('venue_address', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_inquiries', to=settings.AUTH_USER_MODEL)),
                ('catering_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catering.cateringmenu')),
            ],
            options={
                'db_table': 'catering_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
