# Generated by Django 6.0.5 on 2026-06-02 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.URLField(max_length=500)),
                ('redirect_url', models.URLField(blank=True, default='', max_length=500)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date', 'priority'], name='idx_banner_active_dates_priority')],
            },
        ),
    ]
