# Generated by Django 6.0.5 on 2026-06-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='idx_banner_active_priority',
            old_name='idx_banner_active_dates_priority',
        ),
    ]
