# Generated by Django 6.0.5 on 2026-06-16 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_favoriterestaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningVenue',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seating_capacity', models.PositiveIntegerField(default=50)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_outdoor', models.BooleanField(default=False)),
                ('avg_cost_for_two', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_venues', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'dining_venues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('guest_count', models.PositiveSmallIntegerField(default=2)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_reservations', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dining.diningvenue')),
            ],
            options={
                'db_table': 'dining_reservations',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
