# Generated by Django 6.0.5 on 2026-06-16 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_favoriterestaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPackage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('min_guests', models.PositiveIntegerField(default=10)),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_packages', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'party_packages',
                'ordering': ['price_per_person'],
            },
        ),
        migrations.CreateModel(
            name='PartyBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField()),
                ('guest_count', models.PositiveIntegerField(default=10)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_bookings', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parties.partypackage')),
            ],
            options={
                'db_table': 'party_bookings',
                'ordering': ['-event_date'],
            },
        ),
    ]
