# Generated by Django 6.0.5 on 2026-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_savedoffer'),
        ('restaurants', '0006_restaurant_closing_time_restaurant_is_24hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='offers', to='restaurants.restaurant'),
        ),
    ]
