# Generated by Django 6.0.5 on 2026-06-16 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(help_text='e.g. Visa, Mastercard, Paytm', max_length=50)),
                ('card_type', models.CharField(blank=True, help_text='e.g. Credit, Debit, Wallet', max_length=20)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
