# Generated by Django 6.0.5 on 2026-06-16 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSector',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('emoji', models.CharField(default='🍽️', max_length=10)),
                ('bg_gradient_start', models.CharField(default='#FFF0E6', help_text='CSS hex colour for gradient start', max_length=9)),
                ('bg_gradient_end', models.CharField(default='#FFE4CC', help_text='CSS hex colour for gradient end', max_length=9)),
                ('border_color', models.CharField(default='#F5C9A0', max_length=9)),
                ('route', models.CharField(blank=True, default='', help_text="Frontend route key, e.g. 'instamart', 'dining'. Leave blank for 'coming soon'.", max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'app_sectors',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
